name: 'zwift_analytics'
version: '1.0.0'

profile: 'zwift_analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  zwift_analytics:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    core:
      +schema: core
      +materialized: table