zwift_analytics:
  target: "{{ env_var('TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: data/zwift_analytics_dev.duckdb
      threads: 2
    test:
      type: duckdb
      path: "md:zwift_analytics_test?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 2
    prod:
      type: duckdb
      path: "md:zwift_analytics_prod?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 2